### ISSUE TITLE
Sprite Image Overflow

### ISSUE THREAD

**Issue by Snoopy219** [BX-Coding/patch-ide#101]
**Describe the bug**
Sprite images are too long and overflow onto the next sprite.

**To Reproduce**
1. Click the plus
2. Click on 'From built-in'
3. Click on 'Diver 1'
4. See Error

**Expected behavior**
Diver 1 contained in its box.

**Screenshots**
When the sprite is not hovered:
![Image](https://github.com/BX-Coding/patch-ide/assets/78870469/5a7f16e9-d25b-4975-ab16-4d28ebaee868)

When the sprite is hovered:
![Image](https://github.com/BX-Coding/patch-ide/assets/78870469/c7ea7289-7b18-4701-bcd8-f700957974b7)

**Desktop (please complete the following information):**
 - OS: macOS 13.5
 - Browser: chrome
 - Version: 116

**Additional Context**
This seems to happen if the sprite's width/height ratio is greater than the cat

**Comment by ElliotRoe** [comment]
Resolved with #105
